apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: aimodelaccuracy
spec:
  crd:
    spec:
      names:
        kind: AIModelAccuracy
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            accuracyThreshold:
              type: number
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package aimodelaccuracy

        # For Pods
        violation[{"msg": msg}] {
          accuracy := input.review.object.spec.accuracy
          accuracyThreshold := input.parameters.accuracyThreshold * 100
          accuracy < accuracyThreshold
          msg := sprintf("Unacceptable accuracy value %v%%. Accuracy must be greater than or equal to %v%%.", [accuracy, accuracyThreshold])
        }
