---
# The opa-policy Pipeline will run through several tasks:
# - source is pulled from git
# - policy is applied via opa
# - model is copied from ceph s3 to kafka queue
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: opa-policy-pipeline
  namespace: policy-pipeline
spec:
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: model-accuracy-policy
      taskRef:
        name: apply-opa-policy
      resources:
        inputs:
          - name: source
            resource: source-repo
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: apply-opa-policy
  namespace: policy-pipeline
spec:
  inputs:
    resources:
      - name: source
        type: git
  steps:
    - name: apply
      image: instrumenta/conftest:v0.17.0
      command:
        # Actual command name needs to be first because even if entrypoint is
        # set to this command in the image already, the entrypoint is overridden
        # by tekton.
        - conftest
        - test
        - -i
        - json
        - $(inputs.resources.source.path)/outputs/metrics
        - -p
        - $(inputs.resources.source.path)/policy/accuracy.rego
